//
// Created by Steven Imle on 11/27/16.
//

#ifndef INC_4_ERROR_CODES_H
#define INC_4_ERROR_CODES_H


enum ERROR_CODE {
	NO_ERROR = 0,
	INVALID_INPUT_FILE_ERROR = 10,
	INVALID_COMMAND_LINE_ARGUMENT = 11,

	NO_SECTION_PARSER_PROVIDED = 20,

	RS_INVALID_REGISTER_ADDRESS = 50,
	RS_INVALID_SYSCALL = 51,
	RS_INVALID_FUNCTIONAL_UNIT = 52,

	IFU_INVALID_FLAG_TYPE = 60,
	IFU_INVALID_OPC_TYPE = 61,

	SS_INVALID_OPCODE_CAST = 70,
	SS_INVALID_PSEUDO_OPCODE = 71,

	SS_MEMORY_STACK_OVERFLOW = 100,

	SS_SRC_FILE_READ_ERROR = 150,
	SS_SRC_FILE_DECODE_ERROR = 151,

	INVALID_READ_VALUE = 170,

	SRC_FILE_HAS_TOO_MANY_INSTRUCTIONS = 200,
	SRC_FILE_HAS_TOO_MUCH_DATA = 201,
	SRC_FILE_INVALID_DATA_TYPE = 202,
	SRC_FILE_INVALID_DATA_VALUE = 203,
};

void printError(ERROR_CODE error_code);


#endif //INC_4_ERROR_CODES_H
